---
- name: Install prerequisite packages
  loop: "{{ dependencies }}"
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}"

- name: Add the Docker repository to APT sources
  ansible.builtin.deb822_repository:
    name: docker
    types: ["deb"]
    uris: "{{ base_docker_url }}"
    suites: "{{ ansible_distribution_release | lower }}"
    components: stable
    signed_by: "{{ gpg_key_url }}"
    enabled: true

- name: Install Docker
  loop: "{{ docker_packages }}"
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  notify:
    - Enable Docker service

- name: Copy daemon.json
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '644'
  notify:
    - Start Docker service

- name: Create docker group
  ansible.builtin.group:
    name: "{{ docker_group }}"
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: "{{ docker_group }}"
    append: true
  when: user is defined
