---
- name: Install prerequisite packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{ __docker_dependencies }}"

- name: Add the Docker repository to APT sources
  ansible.builtin.deb822_repository:
    name: docker
    types: ["deb"]
    uris: "{{ __docker_base_url }}"
    suites: "{{ ansible_distribution_release | lower }}"
    components: stable
    signed_by: "{{ __docker_gpg_key_url }}"
    enabled: true

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ __docker_packages }}"
    update_cache: true
  notify:
    - Enable Docker service

- name: Copy daemon.json
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '644'
  notify:
    - Start Docker service

- name: Create docker group
  ansible.builtin.group:
    name: "{{ __docker_group }}"
    state: present

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ __docker_group }}"
    append: true
  loop: "{{ docker_list_users }}"
  when: docker_list_users | length > 0
